# ** env **
spring:
  config:
    activate:
      on-profile: "env"

kakao:
  client:
    id: "027af1e1bbd65e2161d454d88f739af6"
    secret: "FTCBzIYWbw0EmCnDDb5EIeRgS3l47Xkz"
  grant:
    type: "authorization_code"
  redirect:
    uri: "http://localhost:8081/kakao"

security:
  key: "yoon-baseball-community"