# ** Common **
spring:
  config:
    activate:
      on-profile: "common"

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /resources/**

# ** Server **
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /